name: Send submodule updates to parent repo

on:
  workflow_dispatch:

jobs:
  update:
    name: 'Submodule Sync'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # checkout the repository to github action runner
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          repository: vanvuvuong/vanvuvuong.github.io
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
          run: |
            echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
            echo "github.workspace = ${{ github.workspace }}"
            echo "pr.ref = ${{github.event.pull_request.head.ref}}"
            echo "github.ref = ${{ github.ref }}"
            echo "$GITHUB_CONTEXT"

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
